// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Academy.Models;

public partial class Attendance
{
    public int Student { get; set; }

    public long Lesson { get; set; }

    public bool Present { get; set; }

    public virtual Schedule LessonNavigation { get; set; }

    public virtual Student StudentNavigation { get; set; }
}