// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Academy.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Academy.Models
{
    public partial interface IPV_521_ImportContextProcedures
    {
        Task<int> sp_InsertAllHolidaysForAsync(short? year, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_InsertHolidaysForAsync(short? year, string holiday, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_InsertLessonAsync(int? group, short? discipline, short? teacher, DateOnly? date, OutputParameter<TimeOnly?> time, OutputParameter<byte?> lesson_number, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_InsertSheduleStacionarAsync(string group_name, string discipline_name, string teacher_first_name, DateOnly? start_date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_SelectScheduleForResult>> sp_SelectScheduleForAsync(string group, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
