// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Academy.Models;

namespace Academy.Models
{
    public partial class PV_521_ImportContext
    {

        [DbFunction("CountLessons", "dbo")]
        public static byte? CountLessons(int? group, short? discipline)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetEasterDate", "dbo")]
        public static DateOnly? GetEasterDate(short? year)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetNewYearHolidaysStartDate", "dbo")]
        public static DateOnly? GetNewYearHolidaysStartDate(short? year)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetNextLeaningDay", "dbo")]
        public static byte? GetNextLeaningDay(string group_name)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetNextLearningDate", "dbo")]
        public static DateOnly? GetNextLearningDate(string group_name, DateOnly? date)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetNextLearningDay", "dbo")]
        public static byte? GetNextLearningDay(string group_name, DateOnly? last_date)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetSummertimeSadness", "dbo")]
        public static DateOnly? GetSummertimeSadness(short? year)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
