// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Academy.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Academy.Models
{
    public partial class PV_521_ImportContext
    {
        private IPV_521_ImportContextProcedures _procedures;

        public virtual IPV_521_ImportContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new PV_521_ImportContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IPV_521_ImportContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class PV_521_ImportContextProcedures : IPV_521_ImportContextProcedures
    {
        private readonly PV_521_ImportContext _context;

        public PV_521_ImportContextProcedures(PV_521_ImportContext context)
        {
            _context = context;
        }

        public virtual async Task<int> sp_InsertAllHolidaysForAsync(short? year, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "year",
                    Value = year ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.SmallInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_InsertAllHolidaysFor] @year = @year", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_InsertHolidaysForAsync(short? year, string holiday, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "year",
                    Value = year ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.SmallInt,
                },
                new SqlParameter
                {
                    ParameterName = "holiday",
                    Size = 150,
                    Value = holiday ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_InsertHolidaysFor] @year = @year, @holiday = @holiday", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_InsertLessonAsync(int? group, short? discipline, short? teacher, DateOnly? date, OutputParameter<TimeOnly?> time, OutputParameter<byte?> lesson_number, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parametertime = new SqlParameter
            {
                ParameterName = "time",
                Scale = 7,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = time?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Time,
            };
            var parameterlesson_number = new SqlParameter
            {
                ParameterName = "lesson_number",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = lesson_number?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.TinyInt,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "group",
                    Value = group ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "discipline",
                    Value = discipline ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.SmallInt,
                },
                new SqlParameter
                {
                    ParameterName = "teacher",
                    Value = teacher ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.SmallInt,
                },
                new SqlParameter
                {
                    ParameterName = "date",
                    Value = date ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                parametertime,
                parameterlesson_number,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_InsertLesson] @group = @group, @discipline = @discipline, @teacher = @teacher, @date = @date, @time = @time OUTPUT, @lesson_number = @lesson_number OUTPUT", sqlParameters, cancellationToken);

            time?.SetValue(parametertime.Value);
            lesson_number?.SetValue(parameterlesson_number.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_InsertSheduleStacionarAsync(string group_name, string discipline_name, string teacher_first_name, DateOnly? start_date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "group_name",
                    Size = 10,
                    Value = group_name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NChar,
                },
                new SqlParameter
                {
                    ParameterName = "discipline_name",
                    Size = 150,
                    Value = discipline_name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "teacher_first_name",
                    Size = 50,
                    Value = teacher_first_name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "start_date",
                    Value = start_date ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_InsertSheduleStacionar] @group_name = @group_name, @discipline_name = @discipline_name, @teacher_first_name = @teacher_first_name, @start_date = @start_date", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_SelectScheduleForResult>> sp_SelectScheduleForAsync(string group, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "group",
                    Size = 10,
                    Value = group ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_SelectScheduleForResult>("EXEC @returnValue = [dbo].[sp_SelectScheduleFor] @group = @group", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
