// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Academy.Models
{
    public partial class sp_SelectScheduleForResult
    {
        public string Группа { get; set; }
        [StringLength(150)]
        public string Дисциплина { get; set; }
        public DateOnly? Дата { get; set; }
        public TimeOnly? Время { get; set; }
        [StringLength(30)]
        public string День { get; set; }
        [StringLength(4000)]
        public string Препод { get; set; }
        [StringLength(13)]
        public string Статус { get; set; }
    }
}
